# -*- coding: utf-8 -*-
"""NaN_Pandas_ML_Complete_Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeVR_qDHJulvevUkqy--wDCXyqVyYWFg

# NaN in Pandas & Machine Learning — Complete Tutorial

This notebook covers:
- What NaN means
- Detecting and counting missing values
- Hidden/fake NaNs
- `dropna()` and `fillna()`
- Mean, median, mode, forward/backward fill
- `SimpleImputer`
- `fit()`, `transform()`, and `fit_transform()`
- Train/test leakage
- NaNs in multiple columns
- NaN propagation and infinity
- Feature engineering problems
- ML pipeline usage
- 10 interview questions with answers

**Designed for Google Colab.**

## 1. What is NaN?

`NaN` means **Not a Number**. In Pandas it is commonly used to represent a missing numerical value.

Important distinction:
- `0` → actual zero
- `NaN` → missing/unknown
- `"NaN"` → a string, not an actual NaN
"""

import numpy as srinithi

srinithi.nan

None

100

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Anu", "Ravi", "Priya"],
    "Age": [25, np.nan, 30]
})

print(df)
print("\nData types:")
print(df.dtypes)

help(numpy.nan)

dir(numpy)

"""## 2. Why is NaN important?

Real-world datasets frequently contain missing information. Missing and zero do not necessarily mean the same thing.
"""

df = pd.DataFrame({
    "Customer": ["A", "B", "C"],
    "Age": [25, np.nan, 0],
    "Salary": [50000, np.nan, 0]
})

print(df)

"""## 3. Where can NaN come from?

NaN can enter through missing cells, data conversion, invalid values, or calculations.

`errors="coerce"` is useful when invalid values should become NaN.
"""

df = pd.DataFrame({
    "Age": ["25", "30", "unknown", "40"]
})

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

print(df)
print(df)

"""## 4. Detect NaN with `isna()`"""

df = pd.DataFrame({
    "Age": [25, np.nan, 30],
    "Salary": [50000, 60000, np.nan]
})

print(df.isna())

"""## 5. `isna()` vs `isnull()`

Both are commonly used and behave equivalently for missing-value detection.
"""

print("isna():")
print(df.isna())

print("\nisnull():")
print(df.isnull())

"""## 6. Count NaN values"""

print(df.isna().sum())

"""## 7. Missing-value percentage"""

missing_percentage = df.isna().mean() * 100
print(missing_percentage)

"""## 8. Hidden or fake NaNs

Real datasets may contain `"NA"`, `"N/A"`, `"null"`, `"unknown"`, `"-"`, `"?"`, or empty strings. These may be strings rather than actual NaN values.
"""

df = pd.DataFrame({
    "Age": [25, "NA", "unknown", 40, np.nan]
})

print(df)
print("\nMissing count:")
print(df.isna().sum())

"""## 9. Convert fake missing values to actual NaN"""

df["Age"] = df["Age"].replace(
    ["NA", "N/A", "null", "None", "unknown", "-", "?"],
    np.nan
)

print(df)
print("\nMissing count:")
print(df.isna().sum())

"""## 10. `"NaN"` string vs actual `NaN`"""

actual_nan = np.nan
string_nan = "NaN"

print("Actual NaN type:", type(actual_nan))
print("String NaN type:", type(string_nan))

print("np.nan == np.nan:", actual_nan == actual_nan)
print('"NaN" == "NaN":', string_nan == "NaN")

"""## 11. Never detect NaN using `==`

`np.nan == np.nan` is `False`. Use `pd.isna()` or `Series.isna()` instead.
"""

"kanmani" == "kanmani"

value = np.nan

print("Wrong comparison:", value == np.nan)
print("Correct check:", pd.isna(value))

df = pd.DataFrame({"Age": [25, np.nan, 30]})
print("\nRows with missing Age:")
print(df[df["Age"].isna()])

"""## 12. Removing rows with `dropna()`

Be careful: dropping rows can remove a large amount of useful training data.
"""

df = pd.DataFrame({
    "Age": [25, np.nan, 35],
    "Salary": [50000, 60000, np.nan]
})

print("Before:")
print(df)

df_clean = df.dropna()

print("\nAfter:")
print(df_clean)

print("\nRows removed:", len(df) - len(df_clean))

"""## 13. Removing columns with `dropna(axis=1)`"""

df_clean = df.dropna(axis=1)
print(df_clean)

"""## 14. Filling NaN with a fixed value

Use this only when the replacement value has a valid business meaning.
"""

df = pd.DataFrame({"Children": [1, 2, np.nan, 0]})

df["Children"] = df["Children"].fillna(0)
print(df)

"""## 15. Mean imputation"""

df = pd.DataFrame({"Age": [20, 30, 40, np.nan, 50]})

mean_age = df["Age"].mean()
df["Age_mean"] = df["Age"].fillna(df["Age"].mean())

print("Mean:", mean_age)
print(df)

"""## 16. Median imputation

Median is often more robust than mean when numerical data is skewed or contains outliers.
"""

df = pd.DataFrame({"Age": [20, 30, 40, np.nan, 50, 500]})

median_age = df["Age"].median()
df["Age_median"] = df["Age"].fillna(median_age)

print("Median:", median_age)
print(df)

"""## 17. Mode imputation for categorical data"""

df = pd.DataFrame({
    "City": ["Chennai", "Mumbai", "Chennai", np.nan, "Chennai"]
})

mode_city = df["City"].mode()[0]
df["City"] = df["City"].fillna(mode_city)

print("Mode:", mode_city)
print(df)

"""## 18. Forward fill and backward fill

These are particularly useful in some time-series situations, when carrying a neighboring value makes domain sense.
"""

df = pd.DataFrame({
    "Day": ["Monday", "Tuesday", "Wednesday"],
    "Temperature": [30, np.nan, 32]
})

print("Original:")
print(df)

df["ffill"] = df["Temperature"].ffill()
df["bfill"] = df["Temperature"].bfill()

print("\nWith forward/backward fill:")
print(df)

"""# 19. `SimpleImputer`

Scikit-learn provides `SimpleImputer` for systematic missing-value preprocessing.
"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mode")

print(imputer)

"""## 20. `fit()` — Learn

`fit()` learns the replacement statistic from the data.

For `strategy="median"`, it calculates and remembers one median **per column**.
"""

X_train_demo = np.array([
    [20, 40000],
    [25, 50000],
    [30, np.nan],
    [40, 80000],
    [50, 90000]
], dtype=float)

imputer = SimpleImputer(strategy="median")
imputer.fit(X_train_demo)

print("Learned statistics:")
print(imputer.statistics_)

"""## 21. `transform()` — Apply

`transform()` applies the statistics learned during `fit()`.
"""

X_train_clean = imputer.transform(X_train_demo)

print("Before:")
print(X_train_demo)

print("\nAfter:")
print(X_train_clean)

"""## 22. `fit_transform()` — Learn + Apply

This:

```python
imputer.fit_transform(X_train)
```

is effectively:

```python
imputer.fit(X_train)
X_train = imputer.transform(X_train)
```
"""

X_train_clean_2 = SimpleImputer(
    strategy="median"
).fit_transform(X_train_demo)

print(X_train_clean_2)

"""## 23. The most important ML rule

**Training data:** `fit_transform()`

**Test data:** `transform()` only

The imputer must learn its statistics only from training data.
"""

X_train = np.array([
    [20, 40000],
    [25, 50000],
    [30, np.nan],
    [40, 80000],
    [50, 90000]
], dtype=float)

X_test = np.array([
    [35, 60000],
    [60, np.nan]
], dtype=float)

imputer = SimpleImputer(strategy="median")

X_train_clean = imputer.fit_transform(X_train)
X_test_clean = imputer.transform(X_test)

print("Learned statistics:", imputer.statistics_)
print("\nClean X_train:")
print(X_train_clean)
print("\nClean X_test:")
print(X_test_clean)

"""## 24. Why not `fit_transform()` on test data?

This is wrong:

```python
X_test = imputer.fit_transform(X_test)
```

It allows the test set to determine its own preprocessing statistics. That is a form of **data leakage**.

Correct:

```python
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)
```

## 25. NaNs in different columns

`SimpleImputer(strategy="median")` calculates the median **independently for each column**.

Example:
- Age has its own median
- Salary has its own median
- Experience has its own median
"""

X = np.array([
    [20, 40000, 2],
    [30, np.nan, 5],
    [np.nan, 60000, 7],
    [50, 70000, np.nan],
    [60, np.nan, 10]
], dtype=float)

imputer = SimpleImputer(strategy="median")
X_clean = imputer.fit_transform(X)

print("Column medians:", imputer.statistics_)
print("\nBefore:")
print(X)
print("\nAfter:")
print(X_clean)

"""## 26. Important example: Salary is NaN for Age 60

If Salary is missing for the person with Age 60, `SimpleImputer` does **not** use Age 60 to predict salary.

It simply uses the median of the Salary column.
"""

df = pd.DataFrame({
    "Age": [20, 30, 40, 50, 60],
    "Salary": [40000, 50000, 60000, 70000, np.nan]
})

print(df)

salary_median = df["Salary"].median()
print("\nSalary median:", salary_median)

df["Salary_imputed"] = df["Salary"].fillna(salary_median)

print("\nAfter imputation:")
print(df)

"""## 27. Limitation of SimpleImputer

SimpleImputer is column-wise. It does not understand relationships such as:

`Age + Experience + Education → Salary`

If you want to estimate a missing Salary based on other features, you need a more sophisticated or predictive imputation approach.
"""

# Conceptual example only:
#
# Age
# Experience
# Education
# Location
#       ↓
# Predictive model
#       ↓
# Estimated Salary

"""## 28. NaN propagation during calculations"""

salary = 50000
bonus = np.nan

print("Salary + Bonus =", salary + bonus)

df = pd.DataFrame({
    "Salary": [50000, 60000, 70000],
    "Bonus": [5000, np.nan, 7000]
})

df["TotalIncome"] = df["Salary"] + df["Bonus"]

print("\nFeature engineering result:")
print(df)

"""## 29. NaN vs Infinity

Division or other numerical operations can produce `inf` as well as `NaN`.

Always check both when debugging numerical ML data.
"""

df = pd.DataFrame({
    "Sales": [100, 200, 300],
    "Customers": [10, 0, np.nan]
})

df["SalesPerCustomer"] = df["Sales"] / df["Customers"]

print(df)

numeric = df.select_dtypes(include="number")

print("\nNaN count:")
print(numeric.isna().sum())

print("\nInfinity count:")
print(np.isinf(numeric).sum())

"""## 30. Feature engineering can introduce NaN

After creating new features, check missing values again.
"""

df = pd.DataFrame({
    "Sales": [100, 200, 300],
    "Customers": [10, np.nan, 0]
})

df["Ratio"] = df["Sales"] / df["Customers"]

print(df)

print("\nMissing values after feature engineering:")
print(df.isna().sum())

"""## 31. Missingness itself can be a feature

Sometimes the fact that a value is missing contains useful information.

Create an indicator column with `isna().astype(int)`."
"""

df = pd.DataFrame({
    "Income": [50000, 60000, np.nan, 70000]
})

df["Income_missing"] = df["Income"].isna().astype(int)

print(df)

"""## 32. Use `Pipeline` for production-style ML preprocessing

Putting preprocessing and the model into one pipeline helps keep training, evaluation, and prediction preprocessing consistent.
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

# Example:
# pipeline.fit(X_train, y_train)
# predictions = pipeline.predict(X_test)

print(pipeline)

"""## 33. NaN debugging checklist"""

# Run these checks when an ML pipeline reports NaN problems.

print("Missing values:")
print(df.isna().sum())

print("\nMissing percentage:")
print(df.isna().mean() * 100)

print("\nData types:")
print(df.dtypes)

numeric = df.select_dtypes(include="number")

print("\nInfinity:")
print(np.isinf(numeric).sum())

print("\nUnique values in each column:")
for column in df.columns:
    print(column, "->", df[column].unique())

"""# 34. Complete ML mental model

```text
RAW DATA
   ↓
Inspect / validate
   ↓
Detect NaN + fake NaN + infinity
   ↓
Train/Test Split
   ↓
X_train ── fit_transform ──→ cleaned X_train
   │
   └── learn preprocessing statistics
                ↓
          X_test ─ transform ─→ cleaned X_test
                ↓
             Model
                ↓
           Evaluation
                ↓
           Deployment
```

**Golden rule:**
- `fit()` = LEARN
- `transform()` = APPLY
- `fit_transform()` = LEARN + APPLY
- Fit preprocessing only on training data.

# Final Cell — 10 NaN Interview Questions & Answers

Run the next cell to print the interview Q&A.
"""

# ============================================================
# NaN — 10 INTERVIEW QUESTIONS & ANSWERS
# ============================================================

interview_questions = [
    (
        "1. What is NaN?",
        "NaN stands for Not a Number. In Pandas it is commonly "
        "used to represent a missing or unavailable numerical value. "
        "It is different from zero because zero is an actual value."
    ),
    (
        "2. How do you detect NaN values in Pandas?",
        "Use isna() or isnull(). For example: "
        "df.isna() and df.isna().sum(). The second is useful for "
        "counting missing values per column."
    ),
    (
        "3. Why doesn't x == np.nan work?",
        "NaN has special floating-point comparison behavior. "
        "Even np.nan == np.nan is False. Use pd.isna(x) or "
        "df[column].isna() instead."
    ),
    (
        "4. What is imputation?",
        "Imputation means replacing missing values with estimated "
        "or selected values. Common approaches include mean, median, "
        "mode, constant values, forward/backward fill, and predictive methods."
    ),
    (
        "5. What is SimpleImputer?",
        "SimpleImputer is a scikit-learn preprocessing class used "
        "to replace missing values. Strategies include mean, median, "
        "most_frequent, and constant."
    ),
    (
        "6. What is the difference between fit() and transform()?",
        "fit() learns information from data. For a median imputer, "
        "fit() calculates and remembers the median of each feature. "
        "transform() applies those learned values. Therefore: "
        "fit = LEARN, transform = APPLY."
    ),
    (
        "7. Why use fit_transform() on training data and transform() "
        "on test data?",
        "The imputer should learn statistics only from training data. "
        "Training uses fit_transform(), while test data uses transform() "
        "with the statistics already learned from training. This prevents "
        "test-set information from leaking into preprocessing."
    ),
    (
        "8. If there are NaNs in Age and Salary, how does "
        "SimpleImputer(strategy='median') work?",
        "It calculates the median independently for each column. "
        "Age gets the Age median and Salary gets the Salary median. "
        "If Salary is missing for a person aged 60, SimpleImputer does "
        "not use Age 60 to predict Salary; it uses the learned Salary median."
    ),
    (
        "9. What is data leakage in missing-value imputation?",
        "Data leakage occurs when test-set information influences "
        "training or preprocessing. A common mistake is calculating "
        "the imputation statistic using the full dataset before splitting. "
        "Correct approach: split first, fit the imputer on X_train, then "
        "transform both X_train and X_test."
    ),
    (
        "10. What are common NaN-related bugs in an ML pipeline?",
        "Common bugs include comparing with == np.nan, hidden strings such "
        "as 'NA' or 'unknown', NaN reaching a model, replacing NaN with zero "
        "without understanding its meaning, fitting on test data, using "
        "different train/test preprocessing, dropping too many rows, creating "
        "NaN during feature engineering, and ignoring infinity values."
    )
]

for question, answer in interview_questions:
    print("=" * 80)
    print(question)
    print("-" * 80)
    print(answer)
    print()